Update terra-jupyter-aou to Hail 0.2.98
DataBiosphere/terra-docker pull request #350
Opened 2022-08-22 22:09 UTC by danking

2022-08-23 15:40 UTC, danking commented
@calbach LMK if you prefer someone else to be assigned!

2022-08-25 16:47 UTC, Qi77Qi commented
cc @yonghaoy ...btw, we recently update gatk image as well, and that change hasn't made it to AoU yet

2022-08-29 17:36 UTC, calbach commented
@danking I'm no longer working on AoU, I defer to @yonghaoy for identifying the right reviewer from the AoU team going forward.

2022-09-06 19:13 UTC, yonghaoy requested changes
https://github.com/DataBiosphere/terra-docker/pull/347/files 2.1.9 is a bad version we should skip that. 
We should use 2.1.10 instead. 
Example: https://github.com/DataBiosphere/terra-docker/blob/master/terra-jupyter-aou/CHANGELOG.md#214---2022-06-03t183522582705z

2022-09-06 19:13 UTC, yonghaoy commented on config/conf.json
> -            },
revert those untouched change

2022-09-13 17:40 UTC, Qi77Qi commented
superceded by https://github.com/DataBiosphere/terra-docker/pull/351

2022-09-13 17:40 UTC, closed without merging